"""create declarations

Revision ID: 1b53a3016141
Revises: dbb5e108513a
Create Date: 2026-09-03 02:40:50.112498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b53a3016141'
down_revision: Union[str, Sequence[str], None] = 'dbb5e108513a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('declarations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('chiffre_affaires', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_ventes', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_achats', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('nombre_employes', sa.Integer(), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('commentaire_admin', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_soumission', sa.DateTime(), nullable=True),
    sa.Column('date_validation', sa.DateTime(), nullable=True),
    sa.Column('traite_par_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['traite_par_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'mois', 'annee', name='uq_declaration_client_mois_annee')
    )
    op.create_index(op.f('ix_declarations_client_id'), 'declarations', ['client_id'], unique=False)
    op.create_index(op.f('ix_declarations_id'), 'declarations', ['id'], unique=False)
    op.create_index(op.f('ix_declarations_statut'), 'declarations', ['statut'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_declarations_statut'), table_name='declarations')
    op.drop_index(op.f('ix_declarations_id'), table_name='declarations')
    op.drop_index(op.f('ix_declarations_client_id'), table_name='declarations')
    op.drop_table('declarations')
    # ### end Alembic commands ###
