"""create taches and factures tables

Revision ID: 49c8ae363c9b
Revises: 3f75053b48f9
Create Date: 2026-09-01 09:45:29.115007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49c8ae363c9b'
down_revision: Union[str, Sequence[str], None] = '3f75053b48f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=True),
    sa.Column('date_emission', sa.DateTime(), nullable=False),
    sa.Column('date_echeance', sa.DateTime(), nullable=True),
    sa.Column('montant_ht', sa.Float(), nullable=False),
    sa.Column('taux_tva', sa.Float(), nullable=False),
    sa.Column('montant_tva', sa.Float(), nullable=False),
    sa.Column('montant_ttc', sa.Float(), nullable=False),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('mode_paiement', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factures_client_id'), 'factures', ['client_id'], unique=False)
    op.create_index(op.f('ix_factures_dossier_id'), 'factures', ['dossier_id'], unique=False)
    op.create_index(op.f('ix_factures_id'), 'factures', ['id'], unique=False)
    op.create_index(op.f('ix_factures_numero'), 'factures', ['numero'], unique=True)
    # NOTE : la table "taches" est déjà créée par la révision 3f75053b48f9
    # ("create taches table"). Sa recréation ici était un doublon généré par
    # erreur (autogenerate exécuté avant que 3f75053b48f9 soit appliquée
    # localement), qui fait échouer "alembic upgrade head" sur une base neuve.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_factures_numero'), table_name='factures')
    op.drop_index(op.f('ix_factures_id'), table_name='factures')
    op.drop_index(op.f('ix_factures_dossier_id'), table_name='factures')
    op.drop_index(op.f('ix_factures_client_id'), table_name='factures')
    op.drop_table('factures')
    # ### end Alembic commands ###
