"""create dossiers table

Revision ID: 5507661edfe5
Revises: 00957c0a803e
Create Date: 2026-08-31 23:56:57.525972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5507661edfe5'
down_revision: Union[str, Sequence[str], None] = '00957c0a803e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dossiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('type_dossier', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('date_ouverture', sa.DateTime(), nullable=False),
    sa.Column('date_cloture', sa.DateTime(), nullable=True),
    sa.Column('priorite', sa.String(length=30), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dossiers_client_id'), 'dossiers', ['client_id'], unique=False)
    op.create_index(op.f('ix_dossiers_id'), 'dossiers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dossiers_id'), table_name='dossiers')
    op.drop_index(op.f('ix_dossiers_client_id'), table_name='dossiers')
    op.drop_table('dossiers')
    # ### end Alembic commands ###
