"""create depenses table

Revision ID: 70c3dc1edc3b
Revises: 93a19a9be6f9
Create Date: 2026-09-01 13:03:54.871648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70c3dc1edc3b'
down_revision: Union[str, Sequence[str], None] = '93a19a9be6f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fournisseur', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('categorie', sa.String(length=100), nullable=False),
    sa.Column('date_depense', sa.DateTime(), nullable=False),
    sa.Column('montant_ht', sa.Float(), nullable=False),
    sa.Column('taux_tva', sa.Float(), nullable=False),
    sa.Column('montant_tva', sa.Float(), nullable=False),
    sa.Column('montant_ttc', sa.Float(), nullable=False),
    sa.Column('mode_paiement', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('justificatif', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_depenses_categorie'), 'depenses', ['categorie'], unique=False)
    op.create_index(op.f('ix_depenses_date_depense'), 'depenses', ['date_depense'], unique=False)
    op.create_index(op.f('ix_depenses_id'), 'depenses', ['id'], unique=False)
    op.create_index(op.f('ix_depenses_reference'), 'depenses', ['reference'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_depenses_reference'), table_name='depenses')
    op.drop_index(op.f('ix_depenses_id'), table_name='depenses')
    op.drop_index(op.f('ix_depenses_date_depense'), table_name='depenses')
    op.drop_index(op.f('ix_depenses_categorie'), table_name='depenses')
    op.drop_table('depenses')
    # ### end Alembic commands ###
