"""add payment operator fields

Revision ID: 820b4ef0a572
Revises: 6413fbf45760
Create Date: 2026-09-01 11:37:00.699875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '820b4ef0a572'
down_revision: Union[str, Sequence[str], None] = '6413fbf45760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paiements', sa.Column('operateur', sa.String(length=30), nullable=True))
    op.add_column('paiements', sa.Column('transaction_id', sa.String(length=100), nullable=True))
    op.add_column('paiements', sa.Column('numero_client', sa.String(length=30), nullable=True))
    op.add_column('paiements', sa.Column('frais', sa.Float(), nullable=True))
    op.execute("UPDATE paiements SET frais = 0 WHERE frais IS NULL")
    op.alter_column(
        'paiements',
        'frais',
        existing_type=sa.Float(),
        nullable=False,
    )
    op.create_index(op.f('ix_paiements_transaction_id'), 'paiements', ['transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paiements_transaction_id'), table_name='paiements')
    op.drop_column('paiements', 'frais')
    op.drop_column('paiements', 'numero_client')
    op.drop_column('paiements', 'transaction_id')
    op.drop_column('paiements', 'operateur')
    # ### end Alembic commands ###
