"""create paiements table

Revision ID: 86da30c919a6
Revises: 49c8ae363c9b
Create Date: 2026-09-01 10:15:06.425120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86da30c919a6'
down_revision: Union[str, Sequence[str], None] = '49c8ae363c9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paiements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facture_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('date_paiement', sa.DateTime(), nullable=False),
    sa.Column('mode_paiement', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paiements_facture_id'), 'paiements', ['facture_id'], unique=False)
    op.create_index(op.f('ix_paiements_id'), 'paiements', ['id'], unique=False)
    op.create_index(op.f('ix_paiements_reference'), 'paiements', ['reference'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paiements_reference'), table_name='paiements')
    op.drop_index(op.f('ix_paiements_id'), table_name='paiements')
    op.drop_index(op.f('ix_paiements_facture_id'), table_name='paiements')
    op.drop_table('paiements')
    # ### end Alembic commands ###
