"""ajout socle comptable SYSCOHADA

Revision ID: ce529efdc7d4
Revises: f1191dd3b062
Create Date: 2026-09-07 17:14:20.629013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce529efdc7d4'
down_revision: Union[str, Sequence[str], None] = 'f1191dd3b062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balances_comptables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercice', sa.Integer(), nullable=False),
    sa.Column('date_balance', sa.DateTime(), nullable=False),
    sa.Column('total_debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_solde_debiteur', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_solde_crediteur', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balances_comptables_exercice'), 'balances_comptables', ['exercice'], unique=False)
    op.create_index(op.f('ix_balances_comptables_id'), 'balances_comptables', ['id'], unique=False)
    op.create_table('comptes_comptables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.Column('classe', sa.String(length=10), nullable=False),
    sa.Column('sous_classe', sa.String(length=10), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comptes_comptables_classe'), 'comptes_comptables', ['classe'], unique=False)
    op.create_index(op.f('ix_comptes_comptables_id'), 'comptes_comptables', ['id'], unique=False)
    op.create_index(op.f('ix_comptes_comptables_numero'), 'comptes_comptables', ['numero'], unique=True)
    op.create_table('periodes_comptables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercice', sa.Integer(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercice', 'mois', name='uq_periode_comptable_exercice_mois')
    )
    op.create_index(op.f('ix_periodes_comptables_exercice'), 'periodes_comptables', ['exercice'], unique=False)
    op.create_index(op.f('ix_periodes_comptables_id'), 'periodes_comptables', ['id'], unique=False)
    op.create_table('ecritures_comptables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periode_id', sa.Integer(), nullable=False),
    sa.Column('date_ecriture', sa.DateTime(), nullable=False),
    sa.Column('journal', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['periode_id'], ['periodes_comptables.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecritures_comptables_date_ecriture'), 'ecritures_comptables', ['date_ecriture'], unique=False)
    op.create_index(op.f('ix_ecritures_comptables_id'), 'ecritures_comptables', ['id'], unique=False)
    op.create_index(op.f('ix_ecritures_comptables_journal'), 'ecritures_comptables', ['journal'], unique=False)
    op.create_index(op.f('ix_ecritures_comptables_periode_id'), 'ecritures_comptables', ['periode_id'], unique=False)
    op.create_index(op.f('ix_ecritures_comptables_reference'), 'ecritures_comptables', ['reference'], unique=False)
    op.create_index(op.f('ix_ecritures_comptables_statut'), 'ecritures_comptables', ['statut'], unique=False)
    op.create_table('lignes_ecritures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecriture_id', sa.Integer(), nullable=False),
    sa.Column('compte_id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=True),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['compte_id'], ['comptes_comptables.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ecriture_id'], ['ecritures_comptables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lignes_ecritures_compte_id'), 'lignes_ecritures', ['compte_id'], unique=False)
    op.create_index(op.f('ix_lignes_ecritures_ecriture_id'), 'lignes_ecritures', ['ecriture_id'], unique=False)
    op.create_index(op.f('ix_lignes_ecritures_id'), 'lignes_ecritures', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lignes_ecritures_id'), table_name='lignes_ecritures')
    op.drop_index(op.f('ix_lignes_ecritures_ecriture_id'), table_name='lignes_ecritures')
    op.drop_index(op.f('ix_lignes_ecritures_compte_id'), table_name='lignes_ecritures')
    op.drop_table('lignes_ecritures')
    op.drop_index(op.f('ix_ecritures_comptables_statut'), table_name='ecritures_comptables')
    op.drop_index(op.f('ix_ecritures_comptables_reference'), table_name='ecritures_comptables')
    op.drop_index(op.f('ix_ecritures_comptables_periode_id'), table_name='ecritures_comptables')
    op.drop_index(op.f('ix_ecritures_comptables_journal'), table_name='ecritures_comptables')
    op.drop_index(op.f('ix_ecritures_comptables_id'), table_name='ecritures_comptables')
    op.drop_index(op.f('ix_ecritures_comptables_date_ecriture'), table_name='ecritures_comptables')
    op.drop_table('ecritures_comptables')
    op.drop_index(op.f('ix_periodes_comptables_id'), table_name='periodes_comptables')
    op.drop_index(op.f('ix_periodes_comptables_exercice'), table_name='periodes_comptables')
    op.drop_table('periodes_comptables')
    op.drop_index(op.f('ix_comptes_comptables_numero'), table_name='comptes_comptables')
    op.drop_index(op.f('ix_comptes_comptables_id'), table_name='comptes_comptables')
    op.drop_index(op.f('ix_comptes_comptables_classe'), table_name='comptes_comptables')
    op.drop_table('comptes_comptables')
    op.drop_index(op.f('ix_balances_comptables_id'), table_name='balances_comptables')
    op.drop_index(op.f('ix_balances_comptables_exercice'), table_name='balances_comptables')
    op.drop_table('balances_comptables')
    # ### end Alembic commands ###
