"""create notifications table

Revision ID: dbb5e108513a
Revises: c549042eafe4
Create Date: 2026-09-03 00:30:58.919390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbb5e108513a'
down_revision: Union[str, Sequence[str], None] = 'c549042eafe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('date_echeance', sa.DateTime(), nullable=True),
    sa.Column('lu', sa.Boolean(), nullable=False),
    sa.Column('date_lecture', sa.DateTime(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_date_echeance'), 'notifications', ['date_echeance'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_lu'), 'notifications', ['lu'], unique=False)
    op.create_index(op.f('ix_notifications_reference_id'), 'notifications', ['reference_id'], unique=False)
    op.create_index(op.f('ix_notifications_reference_type'), 'notifications', ['reference_type'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_utilisateur_id'), 'notifications', ['utilisateur_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_utilisateur_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_reference_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_reference_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_lu'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_date_echeance'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
