"""add client fiscal fields and dossier collaborator

Revision ID: f1191dd3b062
Revises: fa1fb7fb8f69
Create Date: 2026-09-07 15:05:29.262228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1191dd3b062'
down_revision: Union[str, Sequence[str], None] = 'fa1fb7fb8f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('secteur_activite', sa.String(length=150), nullable=True))
    op.add_column('clients', sa.Column('assujetti_tva', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('clients', sa.Column('marge_administree', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('clients', sa.Column('regime_fiscal', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('commune', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('quartier', sa.String(length=150), nullable=True))
    op.add_column('clients', sa.Column('lieu_dit', sa.String(length=150), nullable=True))
    op.add_column('clients', sa.Column('statut_occupation', sa.String(length=30), nullable=True))
    op.add_column('dossiers', sa.Column('collaborateur_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_dossiers_collaborateur_id'), 'dossiers', ['collaborateur_id'], unique=False)
    op.create_foreign_key(None, 'dossiers', 'users', ['collaborateur_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dossiers', type_='foreignkey')
    op.drop_index(op.f('ix_dossiers_collaborateur_id'), table_name='dossiers')
    op.drop_column('dossiers', 'collaborateur_id')
    op.drop_column('clients', 'statut_occupation')
    op.drop_column('clients', 'lieu_dit')
    op.drop_column('clients', 'quartier')
    op.drop_column('clients', 'commune')
    op.drop_column('clients', 'regime_fiscal')
    op.drop_column('clients', 'marge_administree')
    op.drop_column('clients', 'assujetti_tva')
    op.drop_column('clients', 'secteur_activite')
    # ### end Alembic commands ###
